version: '3.8'
services:
holomisha-core:
build:
context: .
dockerfile: Dockerfile
ports:
- "8000:8000"
environment:
- REDIS_HOST=redis-master
depends_on:
- redis-master
redis-master:
image: redis:7.0
ports:
- "6379:6379"
kong:
image: kong:3.0
environment:
- KONG_DATABASE=off
- KONG_PROXY_ACCESS_LOG=/dev/stdout
- KONG_ADMIN_ACCESS_LOG=/dev/stdout
- KONG_PROXY_ERROR_LOG=/dev/stderr
- KONG_ADMIN_ERROR_LOG=/dev/stderr
ports:
- "8001:8001"
prometheus:
image: prom/prometheus:v2.45.0
ports:
- "9090:9090"
grafana:
image: grafana/grafana:9.5.2
ports:
- "3000:3000"